// This file is auto-generated by @hey-api/openapi-ts

export type Body_add_file_s3_file_post = {
  file: Blob | File;
};

export type DocumentOutDTO = {
  document_id: number;
  name: string;
  year?: number | null;
  link: string;
  is_file: boolean;
  subject_name: string;
  teacher_name?: string | null;
  category_name: string;
  semester_num: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type MaterialAddDTO = {
  name: string;
  year?: number | null;
  link: string;
  is_file?: boolean;
  teacher?: string | null;
  subject: string;
  category: string;
  semester_num: number;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type HealthcheckHealthGetResponse = unknown;

export type HealthcheckHealthGetError = unknown;

export type AddMaterialPageResourcePostData = {
  body: MaterialAddDTO;
};

export type AddMaterialPageResourcePostResponse = unknown;

export type AddMaterialPageResourcePostError = unknown | HTTPValidationError;

export type AddFileS3FilePostData = {
  body: Body_add_file_s3_file_post;
  query: {
    document_id: number;
  };
};

export type AddFileS3FilePostResponse = unknown;

export type AddFileS3FilePostError = HTTPValidationError;

export type GetAllDocumentsResourcesGetData = {
  query?: {
    semesterArray?: string | null;
    subjectArray?: string | null;
    subjectTypeArray?: string | null;
    teacherArray?: string | null;
  };
};

export type GetAllDocumentsResourcesGetResponse = Array<DocumentOutDTO>;

export type GetAllDocumentsResourcesGetError = unknown | HTTPValidationError;

export type SearchDocumentSearchGetData = {
  query: {
    limit?: number | null;
    /**
     * Строка для поиска документов по названию, предмету, преподавателю и другим атрибутам.
     */
    prompt: string;
    semesterArray?: string | null;
    subjectArray?: string | null;
    subjectTypeArray?: string | null;
    teacherArray?: string | null;
  };
};

export type SearchDocumentSearchGetResponse = Array<DocumentOutDTO>;

export type SearchDocumentSearchGetError = HTTPValidationError;

export type GetDocumentByIdResourceIdGetData = {
  query: {
    document_id: number;
  };
};

export type GetDocumentByIdResourceIdGetResponse = DocumentOutDTO;

export type GetDocumentByIdResourceIdGetError = unknown | HTTPValidationError;

export type DownloadFileFromS3GetFileLinkGetData = {
  path: {
    link: string;
  };
};

export type DownloadFileFromS3GetFileLinkGetResponse = unknown;

export type DownloadFileFromS3GetFileLinkGetError = HTTPValidationError;
